// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmJmWdA4JjVruIASN2kAryjoVvB37iBIM',
    appId: '1:504597435298:web:6feb21bff3d7f5976358fb',
    messagingSenderId: '504597435298',
    projectId: 'chat-app-23320',
    authDomain: 'chat-app-23320.firebaseapp.com',
    storageBucket: 'chat-app-23320.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcvijdRYT6jS5yhmhOkuX7IChjwHPzEeY',
    appId: '1:504597435298:android:a6089cfe70c01f956358fb',
    messagingSenderId: '504597435298',
    projectId: 'chat-app-23320',
    storageBucket: 'chat-app-23320.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOKL-wO2drGzxGVtPje5OoSVca9c1v3Mc',
    appId: '1:504597435298:ios:f19cf196938fe50e6358fb',
    messagingSenderId: '504597435298',
    projectId: 'chat-app-23320',
    storageBucket: 'chat-app-23320.appspot.com',
    iosClientId: '504597435298-vrjuflt7ejvsfmd14jfjmojs4s14sp9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.betting3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOKL-wO2drGzxGVtPje5OoSVca9c1v3Mc',
    appId: '1:504597435298:ios:ec0794fc67e91a8d6358fb',
    messagingSenderId: '504597435298',
    projectId: 'chat-app-23320',
    storageBucket: 'chat-app-23320.appspot.com',
    iosClientId: '504597435298-gbj1g4ofkvuboo3v1kh71i40rm0flkpm.apps.googleusercontent.com',
    iosBundleId: 'com.example.betting3.RunnerTests',
  );
}
